use healthcare_project;

select * from healthcare;

-- retrive the names of all patients in the database
select name from healthcare;

-- list the unique medical condition present in the dataset
select distinct medical_condition from healthcare;

-- find the total number of doctors in the healthcare system
select count(doctor) from healthcare;

-- retrive the details of all female patients
select * from healthcare where gender = 'female';

-- what is the average age of patients in the database
select avg(age) from healthcare; 

-- identify the patients who have more than one medical condition
select name, medical_condition from healthcare;

-- lit the names of all doctors
select doctor from healthcare;

-- identify the most common medical condition among patients
select medical_condition from healthcare group by medical_condition order by medical_condition desc limit 1;

-- find the patients who are older than 60 years and have diabetes
select * from healthcare where age > 60 and medical_condition = 'diabetes';

-- calculate the total revenue generated by the healthcare system
select sum(billing_amount) from healthcare;

-- find the doctor with the oldest patient
select name, doctor,age, datediff(date_of_admission, discharge_date) from healthcare limit 1;

-- calculate the average duration of medical visits
select avg(duration) from healthcare;

-- give the names of patients whos names start withj 'A'
select name from healthcare where name like 'a%';

-- how many male and female patients are there in database
select gender, count(gender) from healthcare group by gender;

-- how many patients are normal
select name, test_results from healthcare where test_results = 'normal';

-- how many patients are abnormal or inconclusive
select name, test_results from healthcare where test_results = 'abnormal' or test_results = 'inconclusive';

-- how many patients of blood group AB+ and there age is above 52
select name, blood_type, age from healthcare where blood_type = 'AB+' and age > 52;

-- how many patients have paid the bill above 24890
select count(name) from healthcare where billing_amount > 24890;

-- what are the names of patients having asthma
select name, medical_condition from healthcare where medical_condition = 'asthma';

-- how many patients have cancer
select count(name) from healthcare where medical_condition = 'cancer';

-- what are the names and blood groups of patients admitted to room no. 292
select name, blood_type from healthcare where room_number = 292;

-- how many males have arthritis
select count(gender) from healthcare where gender = 'male' and medical_condition = 'arthritis';

-- how many patients were admitted to harris and sons hospital
select count(name) from healthcare where hospital = 'harris and sons';

-- what are the names of patients whos insurance provider are cigna
select name, insurance_provider from healthcare where insurance_provider = 'cigna';

-- name the medical condition having patients whose age is greater than average age
select avg(age) from healthcare;
select medical_condition from healthcare where age > (select avg(age) from healthcare);